name: Python application

on:
  push:
    branches: ["deployment-infrastructure/v_gusakovskiy"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r tasks/deployment-infrastructure/app/requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --show-source --statistics
    - name: Test with pytest
      run: |
        cd tasks/deployment-infrastructure
        pip install pytest pytest-cov
        pytest
